### ISSUE TITLE
Inconsistent verbose

### ISSUE THREAD

**Issue by fatihdinc** [HelmchenLabSoftware/Cascade#47]
Hi Again!

I believe the variable "verbose" is inconsistently labeled, and sometimes not labelled at all (e.g. infer_discrete_spikes). It would be very nice if there was a single global variable that could perfectly silence the output of Cascade, especially for batch processing. Thanks!

**Comment by PTRRupprecht** [comment]
Hi @fatihdinc,

I've now added a ``verbosity`` input argument to the ``utils_discrete_spikes`` function.

There might be still some confusion because there are two variables, ``verbosity`` and ``verbose``, with the first overwritten the second. This is due to historical reasons, and I think it is not worth the effort to make this cleaner as it is today.

Let me know if you think something else needs to be fixed related to this issue.

Peter

**Comment by fatihdinc** [comment]
Thanks!
