### ISSUE TITLE
Same neuron having different noise levels in two trials

### ISSUE THREAD

**Issue by aloejhb** [HelmchenLabSoftware/Cascade#54]
Hi Peter,
I have recorded odor-evoked activities from ~1000 neurons in the olfactory bulb of a zebrafish.
I realized that ~300 neurons of those had different noise level in two different trials (indicated by the [trace_noise_levels variable](https://github.com/HelmchenLabSoftware/Cascade/blob/fe711e3b2f2574aa62dc72357349b7f27d404a49/cascade2p/cascade.py#L351) in cascade.py).
May I ask whether this is a normal phenomenon?
In addition, for the same neuron, should I then use models with different noise level, to predict its spike probabilities in different trials?

**Comment by PTRRupprecht** [comment]
Hi Bo,

Recording 1000 neurons from the zebrafish olfactory bulb sounds quite impressive!

I don't think that there is a reason why the noise level metric should be very different for the same neuron across trials (for example, it would be very unexpected to have a noise level of "1.5" in the first trial, and "7.9" in the second trial). If you see something like this, there might be an error in your processing pipeline.

If the noise level is (modestly) different in two different trials, I would think about how reliable the noise level metric is. A few thoughts:

- The noise level metric becomes less reliable for very short recordings (because then there are fewer data points across which to average the metric).
- The noise level metric becomes less reliable for very low frame rates (because then the variance of the dF/F trace is also more strongly influenced by GCaMP transients).
- The noise level metric works best for sparse GCaMP activity, that is, when the shot noise can be reliably quantified from differences between temporally subsequent data points. For the olfactory bulb, with its high spike rates (compared to other regions of the forebrain), this assumption does probably not hold so well.

Overall, I would guess that the change of noise level might be due to one of the above reasons or a combination thereof. A way to deal with this would be to quantify the noise level not for single trials but on average across trials. This could be done automatically by concatenating the trials and feeding them into Cascade, if this fits your workflow. The default version of Cascade chooses the appropriate noise level by itself.

This said, the output of Cascade models with similar noise levels (e.g., noise "5" and noise "6") is very similar, so I would not worry too much about choosing the right model here, or only if the dataset is very precious and the analyses of the highest importance.

Let me know if this helps you already. And if you have further questions, just let me know, I'm happy to help!

**Comment by aloejhb** [comment]
Hi Peter,
thanks a lot for a detailed reply!
The sizes of ROIs and hence the signal-to-noise ratio has been largely sacrificed in order to record many neurons.
The difference in noise levels from different trial was mostly around 2~3, so it could still be considered modestly different.

For the 3 causes:
The frame rate was 7.5Hz and each trial had 160 frames, so causes 1 and 2 should have some effect.
The 3rd cause sounds interesting. The mean noise level for all neurons from the whole time traces (including odor stimuli period) is 8.87. The mean noise level from the baseline period is 8.32. Thus the high spike rates during stimuli may have some effect on the noise level measurement.

All in all, I will use the average noise level across all trials, as you said. The results so far look convincing, by checking the spike prob traces by eye. Thanks so much!

**Comment by PTRRupprecht** [comment]
Sounds good!
And thanks for sharing your insights!
